spring:
  thymeleaf:
    cache: false
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:D:/.h2/comic
    username: sa
    password: sa
    type: com.zaxxer.hikari.HikariDataSource
    # 最小空闲连接数量
    hikari:
      minimum-idle: 5
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 10
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 连接池母子
      pool-name: MyHikariCP
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
server:
  port: 80
logging:
  level:
    com.gargoylesoftware: off
data:
  comics:
    我为苍生=http://www.gufengmh.com/manhua/woweicangsheng/
    戒魔人=http://www.gufengmh.com/manhua/jiemoren/
    绝品透视=http://www.gufengmh.com/manhua/juepintoushi/
    极道天使=http://www.gufengmh.com/manhua/jidaotianshi/
    我的天劫女友=http://www.gufengmh.com/manhua/wodetianjienvyou/
    红雾=http://www.gufengmh.com/manhua/hongwu/
    花悸=http://www.gufengmh.com/manhua/huaji/
    演平乱志=http://www.gufengmh.com/manhua/yanpingluanzhi/
    生命源代码=http://www.gufengmh.com/manhua/shengmingyuandaima/
    人体培植=http://www.gufengmh.com/manhua/rentipeizhi/
    妖怪名单=http://www.gufengmh.com/manhua/yaoguaimingdan/
    银魂=http://www.gufengmh.com/manhua/yinhun/
    排球少年！！=http://www.gufengmh.com/manhua/paiqiushaonian/

