spring:
  thymeleaf:
    cache: false
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/Users/blackshow/data/h2
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update
